### PR TITLE
15 hann

### LINKED ISSUE #15: Bug: Division by zero error on products
# CRITICAL ISSUE

When the client requests a single product, or all products, the status code is 500 and the response is always the following.

```
ZeroDivisionError at /products
division by zero
```

The most recent feature added by the team was adding an average rating key to each product. You might want to start there and see if there are any `try/catch` blocks you can implement.

### PR DESCRIPTION
**Pull request by hannmalee**
Product average ratings not accounting for products with a rating value of 0. 

## Changes

- added ZeroDivisionError exception on line 64-68 of product.py to add return value of "not applicable" when ZeroDivisionError is thrown due to line 61 remaining unchanged (because there are no ratings to add)

## Requests / Responses

If this PR contains code that defines a new request/response, or changes an existing one, please put the JSON representations here.

**Request**

GET `/products/9` gets product with id of 9

**Response**

HTTP/1.1 200 OK

```json
{
    "id": 9,
    "name": "Celica",
    "price": 1344.43,
    "number_sold": 0,
    "description": "1982 Toyota",
    "quantity": 1,
    "created_date": "2019-08-03",
    "location": "Al ‘Āliyah",
    "image_path": null,
    "average_rating": "not applicable"
}
```

## Testing

In postman: 

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database 
- [ ] open Postman
- [ ] run GET for `/products/9`
- [ ] average_rating key should = "not applicable"

## Related Issues

- Fixes #15

### CODE REVIEW

**Review by gwynnemeeks — CHANGES_REQUESTED** [review]
It looks like there is a disconnect between the PR, the linked ticket, and the code. Please update the PR to reflect both the ticket and description of the code on the branch, so everything is cohesive.

The code appears to be for the divide by zero bug

**Review by heymonicakay — CHANGES_REQUESTED** [review]
Your PR description contains information from the PR template that is not relevant to this PR, and should be removed. Also, the description of the changes made and steps to test are unclear. 

What changes did you make? How can I test your code? What is the expected outcome when I run your code? 

Right now it seems like I'm _only_ supposed to test GET functionality for a single product by the id of 50. However, the issue ticket linked to your PR indicates this is actually a fix for a ZeroDivisionError. As such, please provide step by step instructions on how to test your code, and provide a description of the expected outcome.

Please revise and resubmit!

**Review by heymonicakay — APPROVED** [review]
PR description was clear and concise with easy to follow testing instructions. try..except block properly implemented, and functioning as expected. Nicely done!

**Review by gwynnemeeks — APPROVED** [review]
Code, ticket, and PR description all match. Approved!

**Pull request merged**
